### ISSUE TITLE
Designated service hours hard to enter

### ISSUE THREAD

**Issue by ruthnan** [attendanceproject/djattendance#1075]
- [x] When editing, the calendar function that pops up when selecting does not match the entered data but defaults to the current date. (Could not replicate - @iamsitting)
- [x] Military time is not intuitive. #1079 
- [x] Upon saving, the chronological ordering disappears. #1079 
- [x] Exception Type: MultipleObjectsReturned at /services/service_hours_ta_view
Exception Value: get() returned more than one ServiceAttendance -- it returned 2! 1af8060f6a4201b28f1c0007ae7d92470168acbb

**Comment by JoannaRumbley** [comment]
I believe the chronological order is reversed when saved.

How urgent do we think this issue is? Medium priority?

**Comment by JoannaRumbley** [comment]
@iamsitting Thanks! It's significantly easier to use now. ...Is there a reason why the times should still be editable after saving it? 
Other edits that might be good are:
1. Making the date and time separate, so they don't have to enter the date twice
2. Having an Delete button in each row so trainees can choose which one to delete, instead of only being able to delete the last hours they entered.

Also:
1. The server probably shouldn't allow them to submit 0 hours
2. The "Tasks Performed" text box is so large now. Can we make it smaller (like, half the size, or less)?

**Comment by iamsitting** [comment]
I think it would've been better to make it look like the one on the old server. But we were trying to get something functional. It'd be good for  @xuefeizheng and @isaactsou  (with TAs) to come up with a design before making further UI enhancements.

**Comment by JoannaRumbley** [comment]
I think Xuefei is on it. 👍
