### ISSUE TITLE
Exam Render

### ISSUE THREAD

**Issue by yipingbenjaminliu** [attendanceproject/djattendance#1097]
Apostrophe shows up as u\2039

**Comment by ksungreborn** [comment]
I see \u2019 too, interestingly though on my local server apostrophes work fine...

**Comment by ksungreborn** [comment]
Also interesting is on the dev branch in exams.css we have:
.MCCheckboxes li {
  display: block;
  width: 100%;
  padding-left: 1%;
}
, so that the multiple choice options to appear on their own line, but then on the live server there's still the "float: left;" that makes the options appear on the same line...

**Comment by yipingbenjaminliu** [comment]
we may need to rerun webpack

**Comment by yipingbenjaminliu** [comment]
"float: left" is fine, it's mainly the width adjustment and the bootstrap responsive grid adjustment

**Comment by yipingbenjaminliu** [comment]
#1235 resolves this
