### ISSUE TITLE
Marked for fellowship notification - personal slip

### ISSUE THREAD

**Issue by xuefeizheng** [attendanceproject/djattendance#1123]
- Clicking on the notification for fellowship leads to the login page. 

<img width="589" alt="screen shot 2018-05-05 at 2 23 27 pm" src="https://user-images.githubusercontent.com/33186134/39667719-18333f60-5071-11e8-867e-7ba27b5b6a9f.png">

- It stays on the login page (blank) even if you try to login. 

<img width="749" alt="screen shot 2018-05-05 at 2 23 59 pm" src="https://user-images.githubusercontent.com/33186134/39667654-ffd045c2-506f-11e8-93a5-ac2fb3db2802.png">

**Comment by JoannaRumbley** [comment]
Apparently, clicking on the link directs them to the TA Leave Slip List page. But since they don't have access,  the server redirects them to the login page until they log in as a TA.
@yipingbenjaminliu Can you work on this or reassign to someone?

**Comment by yipingbenjaminliu** [comment]
@ruthnan what was the solution for this?

**Comment by ruthnan** [comment]
ddc6a3b4478c9e948c5cd9057cfd53179cfc7d67

**Comment by JoannaRumbley** [comment]
@ruthnan It looks good on the live server to direct them to their attendance. 👍  But could we make it direct them to that particular leave slip, OR direct them to their attendance for that specific week? Right now, they have to manually click on the right week in order to find out which leave slip is marked. It's probably Low Priority now.
