### ISSUE TITLE
Bible reading tracker

### ISSUE THREAD

**Issue by francestsenn** [attendanceproject/djattendance#1653]
Bible reading tracker causing an error when the trainee is trying to view a week that hasn't occurred yet

Trainee has been getting to the server using ap.ftta.lan/bible_tracker/?week=19, which has been erroring (see the Gmail for the issues)

**Comment by JoannaRumbley** [comment]
PR #1658

**Comment by francestsenn** [comment]
It isn't a problem on Google Chrome, but is one on Safari. Also, it's only affecting one trainee, so I don't know if it's worth fixing  ![bitmoji](https://render.bitstrips.com/v2/cpanel/f4c91480-fbcf-41d6-8afe-2c9b58d18798-f2238d4f-741d-46a3-9124-83f28e6c8f1c-v1.png?transparent=1&palette=1&width=246)

**Comment by JoannaRumbley** [comment]
It looks like they're not supposed to be getting to the week 19 Bible tracker page, so Idk how/why this issue even came up. But if it's a prob when we get to week 19, then it should def be fixed.

I see no issue as it is, since they're not supposed to view a week that hasn't occurred yet...unless I'm misunderstanding it somehow
