### ISSUE TITLE
Find postgres DB backup that only backs up delta's periodically instead of whole db

### ISSUE THREAD

**Issue by radicalray** [attendanceproject/djattendance#168]
Find postgres DB backup that only backs up delta's periodically instead of whole db

I remember there's a way to record postgres transactions and play it back/forward in history. Maybe could use that as delta for preserving the db.

@ricefield @lifedispenser

**Comment by ricefield** [comment]
I'm not familiar with this, but if such a thing exists, I think that would be great.

**Comment by pccchiang** [comment]
Postgres write ahead logs (WAL) which combined with a pg_basebackup allows restoring data up to a point in time. This works by taking a backup and replaying operations from the WAL files to bring the database to a current state. The WAL files need to be taken continuously and can be indefinitely long.

To enable WAL archiving, set the wal_level configuration parameter to archive or higher, archive_mode to on, and specify the shell command to use in the archive_command configuration parameter.

e.g. in the postgres conf file set:
	wal_level = hot_standby
	archive_mode = on
	archive_timeout = #Force a wal file if not full to be written at most some number of seconds
	archive_command = 'cp %p /usr/local/pgsql/pgDataPITR/wals/%f'

Wal backups are 16 MB and can be archived. I archived using tar bzip2 on a log with on a dormant database and reduced the size to 271 B.
	
To restore:
Stop the server, if it's running.

Move or remove the files in the data directory and pg_xlog (which is basically an unwritten WAL file)

Restore the database files from your file system backup. Be sure that they are restored with the right ownership and permisisons.

Remove any files present in pg_xlog/; these came from the file system backup and are therefore probably obsolete rather than current.

If you have unarchived WAL segment files that you saved in step 2, copy them into pg_xlog/. (It is best to copy them, not move them, so you still have the unmodified files if a problem occurs and you have to start over.)

Create a recovery command file recovery.conf in the cluster data directory. An example would be

Temporarily modify pg_hba.conf to prevent ordinary users from connecting until you are sure the recovery was successful.

Start the server. The server will go into recovery mode and proceed to read through the archived WAL files it needs.

Inspect the contents of the database to ensure you have recovered to the desired state.

Reference http://www.postgresql.org/docs/current/static/continuous-archiving.html for more detail.

**Comment by radicalray** [comment]
@pccchiang Hey Peter, looks great! Thanks for digging into this. I wasn't clear about how to set the postgres wal_level configuration parameter as well as how to restore from the backup. Could you paste in some sample config settings + shell commands we can use to do it?

**Comment by radicalray** [comment]
@snowboarder003 Danny, Here's the conversation from before.
