### ISSUE TITLE
MySQL to Postgres Conversion

### ISSUE THREAD

**Issue by radicalray** [attendanceproject/djattendance#186]
Here's a library to help with the conversion potentially for importer module.

https://pypi.python.org/pypi/py-mysql2pgsql

Relevant post on it: https://justin.abrah.ms/databases/converting_from_mysql_to_postgres.html

@haileyl @amarisch

**Comment by allenwebb** [comment]
Did you all see:
https://github.com/attendanceproject/php2django

It may not be named well but it lets you query a MySQL database and tell
django which column to put into which model field. It also keeps track of
the primary key relationship so you can run updates as the MySQL data
changes.
On Apr 8, 2016 23:42, "Ray Li" <notifications@github.com> wrote:

Here's a library to help with the conversion potentially for importer
module.

https://pypi.python.org/pypi/py-mysql2pgsql

Relevant post on it:
https://justin.abrah.ms/databases/converting_from_mysql_to_postgres.html

@haileyl <https://github.com/haileyl> @amarisch
<https://github.com/amarisch>

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub
<https://github.com/attendanceproject/djattendance/issues/186>

**Comment by billyeh** [comment]
Migrating the old database is no longer a requirement.
