### ISSUE TITLE
Cron Jobs (scheduled regular scripts to run)

### ISSUE THREAD

**Issue by radicalray** [attendanceproject/djattendance#248]
@ricefield @vertago1 @snowboarder003 

How are scheduled cron jobs run in the old server? What do we need to cover? Here's what I have so far:

 - [ ] DB (nightly) backup
 - [ ] Calculate Life Study from attendance
 - [ ] Calculate Class note assignment
 - [ ] Absentee roster emails

Please add anything else you know.

We're planning to use ubuntu cron to run our jobs through (Plan (python library)) on the server.

**Comment by vertago1** [comment]
When I was there the absentee roster emails were done by cron, but 
instead by a brother who would input the data every morning. That may 
have changed since then.

I believe the life studies were not automatic either. I recall a TA 
running a weekly report and clicking a link to assign lifestudies 
between weeks. I think this also triggered the classnotes assignments 
too, but I don't remember for sure.

If you are looking for where the database backup was, there are several 
places you may need to check but the first few place I would look are:
1) /etc/cron.daily/
2) sudo crontab -e
3) sudo -u www-data crontab -e

Allen
