### ISSUE TITLE
Duplicate field for house in user meta

### ISSUE THREAD

**Issue by radicalray** [attendanceproject/djattendance#331]
@haileyl how come we have a duplicate house field in user_meta? Is that needed?

There's already a house field in User model.

Same thing for emergency contact:
aputils.models.EmergencyInfo

thanks!

**Comment by billyeh** [comment]
I think we can close this because I don't see the duplicate fields anymore at least. 

There are `house` and `houses` fields on `User` and `UserMeta` but it seems like `houses` is intended for TA use from the comment (TAs being assigned to take care of certain houses?) If we don't think that's needed then we can delete in a separate issue.
