### ISSUE TITLE
Faker Version Bug

### ISSUE THREAD

**Issue by schai6** [attendanceproject/djattendance#384]
Faker version 0.7.3 is installed but gives error when trying to run manage.py:

ImportError: from faker import data

This gets it to work:
pip uninstall faker
pip install "faker<=0.1.4"

**Comment by radicalray** [comment]
Thanks @schai. If this problem is happening on others computers, please update requirements/base.txt or dev.txt to change the version down to the latest working version. This kind of error usually gets caught by TravisCI bot, not sure what happened. 

Make sure error occurs on a clean Dev branch install. Thx!

**Comment by jontey** [comment]
Added version to install in the requirements/base.txt
