### ISSUE TITLE
Bible reading alerts shows anchor string directly in message instead of an actual link

### ISSUE THREAD

**Issue by radicalray** [attendanceproject/djattendance#445]
Looks like this: ```Life Study Summary due for Attendance. <a href="/lifestudies/">Still need: 1</a>```

Don't know if this is already fixed but I saw this on the production server logged into AP

**Comment by jontey** [comment]
Fixed in #448

**Comment by jontey** [comment]
Django bootstrap removed the safe filter in their update on Feb 2016
https://github.com/dyve/django-bootstrap3/commit/d45b5b76afe4fc69f5b3f81e12d653497101ec94#diff-7c210e8010dce79b15a0486cceb453ae
I think the best solution right now would be to just copy over the template code rather than wrangling with the other code.

**Comment by billyeh** [comment]
Nice Jon.

I was also looking into this today and ended up making two possible alternatives we can look into later I'll just put here for the sake of keeping track of.

06dc7a7c418177f55f7fa47eb0e51d5294856339
https://github.com/dyve/django-bootstrap3/pull/352

For our use-case this solution seems simplest, though. We're okay with messages being safe by default.
