### ISSUE TITLE
View Announcements Bug

### ISSUE THREAD

**Issue by yipingbenjaminliu** [attendanceproject/djattendance#575]
clicking on view announcements brings the user into a login page

**Comment by billyeh** [comment]
This is because the urls are messed up for the menu. Trainees can see the link for the TA announcement view. It's also related to Kevin's [comment](https://github.com/attendanceproject/djattendance/pull/570#issuecomment-333683741 ) on #570. The urls shown are missing/incorrect.

We need to have a UX person look at the menu/notifications so we can come up with a standard.

**Comment by billyeh** [comment]
Fixed in #570 thanks @ksungreborn!
