### ISSUE TITLE
Issues with exams

### ISSUE THREAD

**Issue by ruthnan** [attendanceproject/djattendance#609]
Issues to date (4/12/2018):
- [x] No way to view exam on TA side for M/C exams
- [x] Trainee cannot view score because TA cannot finalize the exam for multiple choice because of the is_submitted_online flag.
- [ ] Need to stylize per designers' comments below

Suggestions for exams:
- [x] add a save button
- [x] Bad Request 400 when submitting scores for exams 9e87299ff1197648032ee1d71783cdb75f729faf

**Comment by ruthnan** [comment]
Fixed in #544, my b...

**Comment by finben** [comment]
Moving off of P2 milestone since all of these are UX related versus functional issues except for the Bad Request 400 which was taken care of.

**Comment by xuefeizheng** [comment]
**1.** Change (x) button to "DELETE SECTION" ( to differ from (x) buttons for _Questions_) 

**2.** Use gray (x) buttons next to MCs instead of "Remove Choice"

**3.** Add "Answer(s)" TA can select more than 1 correct answer if needed. (Use vertical layout for MCs) 

**4.** White Space: MCs shift to the right of ADD QUESTION for hierarchy (MC questions are a _sub-section_ of a _Section_)

[More details on "Create Exam" mockup pages.](https://www.dropbox.com/home/attendance%20project/djattendance/Design%20-%20Miriam/Pages/Create%20Exam)

**CURRENT SERVER**
<img width="1366" alt="screen shot 2018-03-31 at 2 27 21 pm" src="https://user-images.githubusercontent.com/33186134/38167802-3665a0fe-34f1-11e8-8357-38ebbe15cd82.png">

**MOCKUP PAGE**
![create exam_3](https://user-images.githubusercontent.com/33186134/38167803-420fd4b0-34f1-11e8-8e21-87ec9dcc1e7c.png)

**Comment by ruthnan** [comment]
@ksungreborn they’re here
