### ISSUE TITLE
Leave slip bugs - schedules don't match

### ISSUE THREAD

**Issue by JoannaRumbley** [attendanceproject/djattendance#896]
1. The time for leave slips don't match time of event. 
2. Schedule for when submitting group leave slips is not the same as the trainee's normal personal schedule that they see.
3. A group leave slip is approved, but it still marks the trainee absent.

**Comment by billyeh** [comment]
Do you remember which trainee that was? @JoannaRumbley 😄

**Comment by JoannaRumbley** [comment]
Sorry @billyeh I don't. :( I'll make sure to mention the name next time. If I notice a trainee page with this problem, I'll mention it here.

**Comment by finben** [comment]
@JoannaRumbley This is because group leave slips are time based. If the time slot selected overlaps even 1 minute with a personal attendance item it will select that event. We are working with the Attendance monitors to have the group leave slip events closer align the personal attendance events but at this point that is all we are going to be able to do. Moving the group events 1 min off from each other did help this issue
