### ISSUE TITLE
TAs to Find and Approve/Mark Leaveslips Easier

### ISSUE THREAD

**Issue by ruthnan** [attendanceproject/djattendance#938]
When user is TA and they are viewing a trainee's leave slip from the "View Personal Attendance" form, they need the ability to approve, mark for fellowship, etc. Sometimes they can't find the leaveslip in the list, so they view attendance via the trainee, so they need a way to approve the leaveslip after looking at it on the trainee side.

**Comment by JoannaRumbley** [comment]
What do you guys think about putting the approve/deny/fellowship buttons right next to each slip like this? @caricchow @xuefeizheng 
![image](https://user-images.githubusercontent.com/33075368/38336153-ab3ed6da-3815-11e8-8118-d114076be8d7.png)

**Comment by finben** [comment]
The only problem is this view uses the same page that a trainee will see. So if we add these buttons it will add it for the trainee view. And we don't want trainee's to be able to approve/deny.

If we can get the slip ID on this page that will help them because they could search it. Ideally, if we get the TA's leave slip list view filter by trainee working and working fast they will not even have to look at it from the trainee side anymore

**Comment by JoannaRumbley** [comment]
I also agree, after hearing what Jerome said before, that we should get the TA Leave Slips page (View Leave Slips) to filter by trainee name first. Then they wouldn't have to look at the trainee side so much.

**Comment by JoannaRumbley** [comment]
...sorry for all the changes

**Comment by iamsitting** [comment]
#1014
